# generated by appcreator
import django_filters
from django import forms
from . models import (
    Actor,
    ArchaeologicalObject4DPuzzleID,
    ArchaeologicalObjectID,
    ArchiveINF,
    AutoCAD,
    BoneInventoryNumber,
    ConvoluteInventoryNumber,
    Convolutecards,
    Datenbase,
    Document4DPuzzleID,
    DocumentTypes,
    ExcavationObjectID,
    ExcavationSeasons,
    Fielddrawing,
    Film,
    Filme,
    FindInventoryNumber,
    Finddrawing,
    Findsheets,
    Fotoborndigital,
    Fotosgescannt,
    Fundinventar4DPuzzleID,
    FundinventarInventarnummern,
    FundinventarKonvolutnummern,
    FundinventarMaterialproben,
    FundinventarSteininventar,
    GIS,
    Geophysics,
    Inventorybooks,
    PhasenID,
    Protocols,
    StratenID,
    TDInv4DPuzzleNUMMER,
    Tables,
    ThreeDimensionalModel,
    Videos,
    WallpaintingInventory
)


class ActorListFilter(django_filters.FilterSet):

    class Meta:
        model = Actor
        fields = [
            'id',
            'access',
            ]


class ArchaeologicalObject4DPuzzleIDListFilter(django_filters.FilterSet):
    archaeological_object_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ArchaeologicalObject4DPuzzleID._meta.get_field('archaeological_object_comment').help_text,
        label=ArchaeologicalObject4DPuzzleID._meta.get_field('archaeological_object_comment').verbose_name
    )
    position = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ArchaeologicalObject4DPuzzleID._meta.get_field('position').help_text,
        label=ArchaeologicalObject4DPuzzleID._meta.get_field('position').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ArchaeologicalObject4DPuzzleID._meta.get_field('digitisation_comment').help_text,
        label=ArchaeologicalObject4DPuzzleID._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = ArchaeologicalObject4DPuzzleID
        fields = [
            'id',
            'archaeological_object_id',
            'archaeological_object_type',
            'archaeological_object_comment',
            'excavation_object_id',
            'position',
            'creator_metadata',
            'digitisation_comment',
            ]


class ArchaeologicalObjectIDListFilter(django_filters.FilterSet):
    archaeological_object_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ArchaeologicalObjectID._meta.get_field('archaeological_object_comment').help_text,
        label=ArchaeologicalObjectID._meta.get_field('archaeological_object_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ArchaeologicalObjectID._meta.get_field('digitisation_comment').help_text,
        label=ArchaeologicalObjectID._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = ArchaeologicalObjectID
        fields = [
            'id',
            'archaeological_object_type',
            'archaeological_object_comment',
            'excavation_object_id',
            'corresponding_to_archaeological_object_id',
            'creator_metadata',
            'digitisation_comment',
            ]


class ArchiveINFListFilter(django_filters.FilterSet):
    comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ArchiveINF._meta.get_field('comment').help_text,
        label=ArchiveINF._meta.get_field('comment').verbose_name
    )

    class Meta:
        model = ArchiveINF
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'relatedto',
            'creation_date_archivalobject',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'comment',
            ]


class AutoCADListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=AutoCAD._meta.get_field('original_comment').help_text,
        label=AutoCAD._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=AutoCAD._meta.get_field('digitisation_comment').help_text,
        label=AutoCAD._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = AutoCAD
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'excavation_object_id',
            'archaeological_object_id',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class BoneInventoryNumberListFilter(django_filters.FilterSet):

    class Meta:
        model = BoneInventoryNumber
        fields = [
            'id',
            ]


class ConvoluteInventoryNumberListFilter(django_filters.FilterSet):

    class Meta:
        model = ConvoluteInventoryNumber
        fields = [
            'id',
            ]


class ConvolutecardsListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Convolutecards._meta.get_field('original_comment').help_text,
        label=Convolutecards._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Convolutecards._meta.get_field('digitisation_comment').help_text,
        label=Convolutecards._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Convolutecards
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'creation_date_original',
            'creation_year_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_dpi',
            'creator_scan',
            'original_material',
            'season',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class DatenbaseListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Datenbase._meta.get_field('original_comment').help_text,
        label=Datenbase._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Datenbase._meta.get_field('digitisation_comment').help_text,
        label=Datenbase._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Datenbase
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'excavation_object_id',
            'archaeological_object_id',
            'find_material',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class Document4DPuzzleIDListFilter(django_filters.FilterSet):
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Document4DPuzzleID._meta.get_field('digitisation_comment').help_text,
        label=Document4DPuzzleID._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Document4DPuzzleID
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creator_metadata',
            'digitisation_comment',
            ]


class DocumentTypesListFilter(django_filters.FilterSet):
    description = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=DocumentTypes._meta.get_field('description').help_text,
        label=DocumentTypes._meta.get_field('description').verbose_name
    )

    class Meta:
        model = DocumentTypes
        fields = [
            'id',
            'analogue_borndigital',
            'description',
            ]


class ExcavationObjectIDListFilter(django_filters.FilterSet):
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ExcavationObjectID._meta.get_field('digitisation_comment').help_text,
        label=ExcavationObjectID._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = ExcavationObjectID
        fields = [
            'id',
            'excavation_object_type',
            'site_id',
            'area',
            'square_trench',
            'planum',
            'year',
            'season',
            'creator_metadata',
            'digitisation_comment',
            ]


class ExcavationSeasonsListFilter(django_filters.FilterSet):

    class Meta:
        model = ExcavationSeasons
        fields = [
            'id',

            'season',
            'access',
            ]


class FielddrawingListFilter(django_filters.FilterSet):
    stratum_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fielddrawing._meta.get_field('stratum_comment').help_text,
        label=Fielddrawing._meta.get_field('stratum_comment').verbose_name
    )
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fielddrawing._meta.get_field('original_comment').help_text,
        label=Fielddrawing._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fielddrawing._meta.get_field('digitisation_comment').help_text,
        label=Fielddrawing._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Fielddrawing
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_original',
            'creation_year_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_ppi',
            'creator_scan',
            'original_material',
            'amendment_drawn_by',
            'drawer_monogram',
            'excavation_object_id',
            'archaeological_object_id',
            'stratum_comment',
            'season',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class FilmListFilter(django_filters.FilterSet):
    decomposition_phenomenon = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Film._meta.get_field('decomposition_phenomenon').help_text,
        label=Film._meta.get_field('decomposition_phenomenon').verbose_name
    )
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Film._meta.get_field('original_comment').help_text,
        label=Film._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Film._meta.get_field('digitisation_comment').help_text,
        label=Film._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Film
        fields = [
            'id',
            'creation_year_original',
            'film_number',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_metadata',
            'creator_metadata',
            'film_format',
            'film_brand',
            'equipment_camera_brand',
            'decomposition_phenomenon',
            'original_material',
            'original_comment',
            'digitisation_comment',
            ]


class FilmeListFilter(django_filters.FilterSet):

    class Meta:
        model = Filme
        fields = [
            'id',
            ]


class FindInventoryNumberListFilter(django_filters.FilterSet):

    class Meta:
        model = FindInventoryNumber
        fields = [
            'id',
            ]


class FinddrawingListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Finddrawing._meta.get_field('original_comment').help_text,
        label=Finddrawing._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Finddrawing._meta.get_field('digitisation_comment').help_text,
        label=Finddrawing._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Finddrawing
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'source_original_copy_edited_copy',
            'resolution_scan_dpi',
            'creator_scan',
            'original_material',
            'find_inventory_number',
            'convolute_inventory_number',
            'bone_stone_inventory_number',
            'find_date',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class FindsheetsListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Findsheets._meta.get_field('original_comment').help_text,
        label=Findsheets._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Findsheets._meta.get_field('digitisation_comment').help_text,
        label=Findsheets._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Findsheets
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'creation_date_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'storage_original',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_dpi',
            'creator_scan',
            'original_material',
            'find_inventory_number',
            'convolute_inventory_number',
            'bone_stone_inventory_number',
            'excavation_object_id',
            'archaeological_object_id',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class FotoborndigitalListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fotoborndigital._meta.get_field('original_comment').help_text,
        label=Fotoborndigital._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fotoborndigital._meta.get_field('digitisation_comment').help_text,
        label=Fotoborndigital._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Fotoborndigital
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_metadata',
            'creator_metadata',
            'copyright',
            'access',
            'site_id',
            'excavation_object_id',
            'original_comment',
            'digitisation_comment',
            ]


class FotosgescanntListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fotosgescannt._meta.get_field('original_comment').help_text,
        label=Fotosgescannt._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fotosgescannt._meta.get_field('digitisation_comment').help_text,
        label=Fotosgescannt._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Fotosgescannt
        fields = [
            'id',
            'film_number',
            'photo_number',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbreviation',
            'creation_date_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_ppi',
            'creator_scan',
            'film_id',
            'excavation_object_id',
            'archaeological_object_id',
            'archaeological_object_type',
            'find_type',
            'find_material',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class Fundinventar4DPuzzleIDListFilter(django_filters.FilterSet):
    find_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fundinventar4DPuzzleID._meta.get_field('find_comment').help_text,
        label=Fundinventar4DPuzzleID._meta.get_field('find_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Fundinventar4DPuzzleID._meta.get_field('digitisation_comment').help_text,
        label=Fundinventar4DPuzzleID._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Fundinventar4DPuzzleID
        fields = [
            'id',
            'find_material',
            'find_type',
            'find_comment',
            'excavation_object_id',
            'access',
            'uncertainty_excavation_digitisation',
            'creator_metadata',
            'digitisation_comment',
            ]


class FundinventarInventarnummernListFilter(django_filters.FilterSet):
    find_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=FundinventarInventarnummern._meta.get_field('find_comment').help_text,
        label=FundinventarInventarnummern._meta.get_field('find_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=FundinventarInventarnummern._meta.get_field('digitisation_comment').help_text,
        label=FundinventarInventarnummern._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = FundinventarInventarnummern
        fields = [
            'id',
            'find_material',
            'find_type',
            'find_comment',
            'excavation_object_id',
            'archaeological_object_id',
            'access',
            'uncertainty_excavation_digitisation',
            'creator_metadata',
            'digitisation_comment',
            ]


class FundinventarKonvolutnummernListFilter(django_filters.FilterSet):
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=FundinventarKonvolutnummern._meta.get_field('digitisation_comment').help_text,
        label=FundinventarKonvolutnummern._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = FundinventarKonvolutnummern
        fields = [
            'id',
            'excavation_object_id',
            'archaeological_object_id',
            'access',
            'creator_metadata',
            'digitisation_comment',
            ]


class FundinventarMaterialprobenListFilter(django_filters.FilterSet):
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=FundinventarMaterialproben._meta.get_field('digitisation_comment').help_text,
        label=FundinventarMaterialproben._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = FundinventarMaterialproben
        fields = [
            'id',
            'find_material',
            'find_type',
            'excavation_object_id',
            'archaeological_object_id',
            'access',
            'relatedto',
            'creator_metadata',
            'digitisation_comment',
            ]


class FundinventarSteininventarListFilter(django_filters.FilterSet):
    find_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=FundinventarSteininventar._meta.get_field('find_comment').help_text,
        label=FundinventarSteininventar._meta.get_field('find_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=FundinventarSteininventar._meta.get_field('digitisation_comment').help_text,
        label=FundinventarSteininventar._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = FundinventarSteininventar
        fields = [
            'id',
            'find_material',
            'find_type',
            'find_comment',
            'excavation_object_id',
            'archaeological_object_id',
            'access',
            'creator_metadata',
            'digitisation_comment',
            ]


class GISListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=GIS._meta.get_field('original_comment').help_text,
        label=GIS._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=GIS._meta.get_field('digitisation_comment').help_text,
        label=GIS._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = GIS
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_original',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'excavation_object_id',
            'archaeological_object_id',
            'relatedto',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class GeophysicsListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Geophysics._meta.get_field('original_comment').help_text,
        label=Geophysics._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Geophysics._meta.get_field('digitisation_comment').help_text,
        label=Geophysics._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Geophysics
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_original',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'method',
            'equipment',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'excavation_object_id',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class InventorybooksListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Inventorybooks._meta.get_field('original_comment').help_text,
        label=Inventorybooks._meta.get_field('original_comment').verbose_name
    )

    class Meta:
        model = Inventorybooks
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'creation_date_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_dpi',
            'creator_scan',
            'original_material',
            'find_inventory_number',
            'convolute_inventory_number',
            'bone_stone_inventory_number',
            'excavation_post_excavation',
            'original_comment',
            ]


class PhasenIDListFilter(django_filters.FilterSet):

    class Meta:
        model = PhasenID
        fields = [
            'id',
            'phase_type',
            'site_id',
            'area',
            ]


class ProtocolsListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Protocols._meta.get_field('original_comment').help_text,
        label=Protocols._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Protocols._meta.get_field('digitisation_comment').help_text,
        label=Protocols._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Protocols
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'creation_date_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'storage',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_dpi',
            'creator_scan',
            'original_material',
            'excavation_object_id',
            'archaeological_object_id',
            'number_of_pages',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class StratenIDListFilter(django_filters.FilterSet):

    class Meta:
        model = StratenID
        fields = [
            'id',
            'stratum_type',
            'site_id',
            'area',
            ]


class TDInv4DPuzzleNUMMERListFilter(django_filters.FilterSet):

    class Meta:
        model = TDInv4DPuzzleNUMMER
        fields = [
            'id',
            ]


class TablesListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Tables._meta.get_field('original_comment').help_text,
        label=Tables._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Tables._meta.get_field('digitisation_comment').help_text,
        label=Tables._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Tables
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'excavation_object_id',
            'archaeological_object_id',
            'relatedto',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class ThreeDimensionalModelListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ThreeDimensionalModel._meta.get_field('original_comment').help_text,
        label=ThreeDimensionalModel._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=ThreeDimensionalModel._meta.get_field('digitisation_comment').help_text,
        label=ThreeDimensionalModel._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = ThreeDimensionalModel
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'creator_archivalobject',
            'excavation_object_id',
            'archaeological_object_id',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]


class VideosListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Videos._meta.get_field('original_comment').help_text,
        label=Videos._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=Videos._meta.get_field('digitisation_comment').help_text,
        label=Videos._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = Videos
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'document_subtype',
            'dst_abbr',
            'creation_date_original',
            'creation_date_archivalobject',
            'file_extension_original',
            'file_extension_archivalobject',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'creator_archivalobject',
            'copyright',
            'access',
            'site_id',
            'find_inventory_number',
            'excavation_object_id',
            'archaeological_object_id',
            'original_comment',
            'digitisation_comment',
            ]


class WallpaintingInventoryListFilter(django_filters.FilterSet):
    original_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=WallpaintingInventory._meta.get_field('original_comment').help_text,
        label=WallpaintingInventory._meta.get_field('original_comment').verbose_name
    )
    digitisation_comment = django_filters.CharFilter(
        lookup_expr='icontains',
        help_text=WallpaintingInventory._meta.get_field('digitisation_comment').help_text,
        label=WallpaintingInventory._meta.get_field('digitisation_comment').verbose_name
    )

    class Meta:
        model = WallpaintingInventory
        fields = [
            'id',
            'document_type',
            'dt_abbr',
            'creation_date_original',
            'creation_date_scan',
            'file_extension',
            'creation_date_metadata',
            'creator_metadata',
            'creator_original',
            'copyright',
            'access',
            'site_id',
            'equipment_scan',
            'source_original_copy_edited_copy',
            'resolution_scan_dpi',
            'creator_scan',
            'original_material',
            'excavation_post_excavation',
            'original_comment',
            'digitisation_comment',
            ]
