# generated by appcreator
from django.urls import path
from . import views

app_name = "filechecker"
urlpatterns = [
    path(
        "fccollection/",
        views.FcCollectionListView.as_view(),
        name="fccollection_browse",
    ),
    path(
        "fccollection/detail/<int:pk>",
        views.FcCollectionDetailView.as_view(),
        name="fccollection_detail",
    ),
    path(
        "fccollection/create/",
        views.FcCollectionCreate.as_view(),
        name="fccollection_create",
    ),
    path(
        "fccollection/edit/<int:pk>",
        views.FcCollectionUpdate.as_view(),
        name="fccollection_edit",
    ),
    path(
        "fccollection/delete/<int:pk>",
        views.FcCollectionDelete.as_view(),
        name="fccollection_delete",
    ),
    path("fcresource/", views.FcResourceListView.as_view(), name="fcresource_browse"),
    path(
        "fcresource/detail/<int:pk>",
        views.FcResourceDetailView.as_view(),
        name="fcresource_detail",
    ),
    path(
        "fcresource/create/",
        views.FcResourceCreate.as_view(),
        name="fcresource_create",
    ),
    path(
        "fcresource/edit/<int:pk>",
        views.FcResourceUpdate.as_view(),
        name="fcresource_edit",
    ),
    path(
        "fcresource/delete/<int:pk>",
        views.FcResourceDelete.as_view(),
        name="fcresource_delete",
    ),
]
