# Generated by Django 2.2.6 on 2019-10-17 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archiv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='digitisation_comment',
        ),
        migrations.AddField(
            model_name='actor',
            name='drawer_monogram',
            field=models.CharField(blank=True, max_length=250, verbose_name='Drawer Monogram'),
        ),
        migrations.AddField(
            model_name='actor',
            name='excavation',
            field=models.CharField(blank=True, max_length=250, verbose_name='Excavation'),
        ),
        migrations.AddField(
            model_name='actor',
            name='first_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='First name'),
        ),
        migrations.AddField(
            model_name='actor',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='actor',
            name='xx_4dpuzzle',
            field=models.CharField(blank=True, max_length=250, verbose_name='4DPuzzle'),
        ),
        migrations.AddField(
            model_name='actor',
            name='year',
            field=models.CharField(blank=True, max_length=250, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='archaeologicalobject4dpuzzleid',
            name='archaeological_object_4dpuzzle_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Archaeological object 4DPuzzle ID'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='archaeological_object_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Archaeological object ID'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='phase_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Phase ID'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='position',
            field=models.CharField(blank=True, max_length=250, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='relatedto',
            field=models.CharField(blank=True, max_length=250, verbose_name='File is related to other TD resources'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='stratum_comment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Stratum comment'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='stratum_id_absolute_prepub',
            field=models.CharField(blank=True, max_length=250, verbose_name='Stratum ID absolute pre publication'),
        ),
        migrations.AddField(
            model_name='archaeologicalobjectid',
            name='stratum_id_relative',
            field=models.CharField(blank=True, max_length=250, verbose_name='Stratum ID relative'),
        ),
        migrations.AddField(
            model_name='archiveinf',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year original'),
        ),
        migrations.AddField(
            model_name='archiveinf',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='archiveinf',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='archiveinf',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year original'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='path_filename_arche',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in ARCHE'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='autocad',
            name='relatedto',
            field=models.CharField(blank=True, max_length=250, verbose_name='File is related to other TD resources'),
        ),
        migrations.AddField(
            model_name='boneinventorynumber',
            name='boneinventorynumber_f',
            field=models.CharField(blank=True, max_length=250, verbose_name='BoneInventoryNumber_f'),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='convolute_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='convolute_subnumber',
            field=models.CharField(blank=True, max_length=250, verbose_name='Convolute subnumber'),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='filename_document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='lowest_height_meters_standard_elevation_zero',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='maximum_height_meters_standard_elevation_zero',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='month',
            field=models.CharField(blank=True, max_length=250, verbose_name='Month'),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='position',
            field=models.CharField(blank=True, max_length=250, verbose_name='Position'),
        ),
        migrations.AddField(
            model_name='convolutecards',
            name='storage_folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage folder of original document'),
        ),
        migrations.AddField(
            model_name='convoluteinventorynumber',
            name='convoluteinventorynumber_f',
            field=models.CharField(blank=True, max_length=250, verbose_name='ConvoluteInventoryNumber_f'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year original'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='path_filename_arche',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in ARCHE'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='datenbase',
            name='relatedto',
            field=models.CharField(blank=True, max_length=250, verbose_name='File is related to other TD resources'),
        ),
        migrations.AddField(
            model_name='document4dpuzzleid',
            name='corresponding_to',
            field=models.CharField(blank=True, max_length=250, verbose_name=''),
        ),
        migrations.AddField(
            model_name='document4dpuzzleid',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='document4dpuzzleid',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='document4dpuzzleid',
            name='original_4dpuzzle_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='document_subtype',
            field=models.CharField(blank=True, help_text='Subtype of a document. ', max_length=250, verbose_name='Document Subtype'),
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='document_type',
            field=models.CharField(blank=True, help_text='Type of document.', max_length=250, verbose_name='Document type'),
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='ds_abbr',
            field=models.CharField(blank=True, help_text='Abbreviation of the document subtype.', max_length=250, verbose_name='Document subtype abbreviated'),
        ),
        migrations.AddField(
            model_name='documenttypes',
            name='dt_abbr',
            field=models.CharField(blank=True, help_text='Abbreviation of the document.', max_length=250, verbose_name='Document type abbreviated'),
        ),
        migrations.AddField(
            model_name='excavationobjectid',
            name='excavation_object_id',
            field=models.CharField(blank=True, help_text='Identifier of an excavation object (excavation objects are objects that were created during excavation). Consists of Site_area_square_TypeOfObject, for example TD_A-II_l17_Planum1.', max_length=250, verbose_name='Identifier of Excavation Object'),
        ),
        migrations.AddField(
            model_name='excavationobjectid',
            name='profile_orientation',
            field=models.CharField(blank=True, help_text='The orientation of a profile.', max_length=250, verbose_name='Orientation of a profile'),
        ),
        migrations.AddField(
            model_name='excavationseasons',
            name='grabungskampagnen',
            field=models.CharField(blank=True, max_length=250, verbose_name='Excavations Seasons'),
        ),
        migrations.AddField(
            model_name='excavationseasons',
            name='year',
            field=models.CharField(blank=True, max_length=250, verbose_name='Year'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='amendment_data',
            field=models.CharField(blank=True, help_text='Date when the amendment was made.', max_length=250, verbose_name='Amendment date'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='document_id',
            field=models.CharField(blank=True, help_text='The project-specific unique identifier of the document which was scanned. It consists of the abbreviation for the site (TD for Tell el-Daba), the abbreviation for the document type (FZ for Feldzeichnung) and an inventory number (or, if there was no inventory number, an ID with the prefix 4DPuzzle was created, e.g. 4DPuzzle1234). For example document ID �TD_FZ_1234� means �Tell el-Daba_field drawing_inventory number 1234�).', max_length=250, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='document_title',
            field=models.CharField(blank=True, help_text='A description of the content of the document.  It allows information about the contents of the file to be understood by a human being without opening it. For field drawings the document title consists of abbreviation for site_excavation area_square trench_content of field drawing (e.g.: TD_F-I_j21_Planum1).', max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='filename',
            field=models.CharField(blank=True, help_text='Consists of document_ID and document_title, separated by two underscores. For example file name �TD_FZ_1234__TD_F-I_j21_Planum1� consists of the document_ID �TD_FZ_1234� which is separated by two underscores from the document title describing the contents of the document �TD(Tell el-Daba)_F/I(area)_j21(square)_ Planum 1�.', max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='find_inventory_number',
            field=models.CharField(blank=True, help_text='Inventory number of a find which is shown on the fielddrawing.', max_length=250, verbose_name='Inventory number of a find drawn on the fielddrawing'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='month',
            field=models.CharField(blank=True, help_text='Month when the field drawing was made.', max_length=250, verbose_name='Fieldwork month'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='original_inventory_number',
            field=models.CharField(blank=True, help_text='Inventory number of the original. An inventory number was given to each field drawing during the excavations. The inventory number is part of the unique identifier of the field drawing. If a field drawing did not have an inventory number, or there was an error with the inventory number, then a new inventory number consisting of the project name �4DPuzzle� and a running number was created, e.g.: 4DPuzzle1234). The list of the new inventory numbers is kept in the Excel file �Metadaten.xlsl�, worksheet  �Resource_4DPuzzle_number�).', max_length=250, verbose_name='Inventory number of original'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='scale',
            field=models.CharField(blank=True, help_text='Drawing scale of the field drawing.', max_length=250, verbose_name='Scale of drawing'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='storage_folder_original',
            field=models.CharField(blank=True, help_text='The text on the label of the folder in the analogue TD archive, where the original is held.', max_length=250, verbose_name='Title of the folder where the original fielddrawing is kept'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='stratum_id_absolute_prepub',
            field=models.CharField(blank=True, help_text='Unique identifier of an absolute stratum. An absolute stratum is a group of stratigraphic units which were confirmed to belong to a chronological phase during post-excavation analysis but before publication (the ID contains: abbreviation of site_excavation area_absolute stratum e.g.: TD_F-I_A is the ID of the absolute stratum A in area F-I in Tell el-Daba). ', max_length=250, verbose_name='Stratum (absolute)'),
        ),
        migrations.AddField(
            model_name='fielddrawing',
            name='stratum_id_relative',
            field=models.CharField(blank=True, help_text='Unique identifier of a relative stratum. Relative stratum is a group of stratigraphic units which are thought to belong to a chronological phase (the ID contains: abbreviation of site_excavation area_relative stratum e.g.: TD_F-I_a is the ID of stratum a in area F-I in Tell el-Daba).', max_length=250, verbose_name='Stratum (relative)'),
        ),
        migrations.AddField(
            model_name='film',
            name='acetic_acid_smell',
            field=models.CharField(blank=True, max_length=250, verbose_name='Acetic acid smell'),
        ),
        migrations.AddField(
            model_name='film',
            name='addition_film_identifier',
            field=models.CharField(blank=True, max_length=250, verbose_name='Addition film identifier'),
        ),
        migrations.AddField(
            model_name='film',
            name='contact_print_present',
            field=models.CharField(blank=True, max_length=250, verbose_name='Contact print present'),
        ),
        migrations.AddField(
            model_name='film',
            name='enlargements_present',
            field=models.CharField(blank=True, max_length=250, verbose_name='Enlargements presten'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Film ID'),
        ),
        migrations.AddField(
            model_name='film',
            name='foto_numbers_missing',
            field=models.CharField(blank=True, max_length=250, verbose_name='Foto numbers missing'),
        ),
        migrations.AddField(
            model_name='film',
            name='storage_folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage folder original'),
        ),
        migrations.AddField(
            model_name='filme',
            name='filme_f',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filme_f'),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='equipment',
            field=models.CharField(blank=True, max_length=250, verbose_name='Equiment'),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='rendered_in_ink',
            field=models.CharField(blank=True, max_length=250, verbose_name='Rendered in ink'),
        ),
        migrations.AddField(
            model_name='finddrawing',
            name='storage_folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage folder of original document'),
        ),
        migrations.AddField(
            model_name='findinventorynumber',
            name='findinventorynumber_f',
            field=models.CharField(blank=True, max_length=250, verbose_name='FindInventoryNumber_f'),
        ),
        migrations.AddField(
            model_name='findsheets',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='findsheets',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='findsheets',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='findsheets',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='findsheets',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year original'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='find_inventory_number_from_to',
            field=models.CharField(blank=True, max_length=250, verbose_name='Inventory number of a find '),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='folder_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Folder ID'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='folder_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Folder name'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='folder_name_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Old folder name'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='folder_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Folder title'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='path_filename_arche',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in ARCHE'),
        ),
        migrations.AddField(
            model_name='fotoborndigital',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old '),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='find_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Find inventor number'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='pixel_size',
            field=models.CharField(blank=True, max_length=250, verbose_name='Pixel size'),
        ),
        migrations.AddField(
            model_name='fotosgescannt',
            name='season',
            field=models.CharField(blank=True, max_length=250, verbose_name='Season '),
        ),
        migrations.AddField(
            model_name='fundinventar4dpuzzleid',
            name='find_inventory_4dpuzzle_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Find inventory 4DPuzzle number'),
        ),
        migrations.AddField(
            model_name='fundinventarinventarnummern',
            name='convolute_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Convolute inventory number'),
        ),
        migrations.AddField(
            model_name='fundinventarinventarnummern',
            name='find_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Find inventory number'),
        ),
        migrations.AddField(
            model_name='fundinventarinventarnummern',
            name='find_local_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Find local number'),
        ),
        migrations.AddField(
            model_name='fundinventarinventarnummern',
            name='storage_find',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage of find'),
        ),
        migrations.AddField(
            model_name='fundinventarkonvolutnummern',
            name='convolute_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Convolute inventory number'),
        ),
        migrations.AddField(
            model_name='fundinventarkonvolutnummern',
            name='convolute_subnumber',
            field=models.CharField(blank=True, max_length=250, verbose_name='Convolute subnumber'),
        ),
        migrations.AddField(
            model_name='fundinventarkonvolutnummern',
            name='relatedto',
            field=models.CharField(blank=True, max_length=250, verbose_name='File is related to other TD resources'),
        ),
        migrations.AddField(
            model_name='fundinventarmaterialproben',
            name='material_sample_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Material sample inventory number'),
        ),
        migrations.AddField(
            model_name='fundinventarsteininventar',
            name='find_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Find inventory number'),
        ),
        migrations.AddField(
            model_name='geophysics',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='geophysics',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='geophysics',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='geophysics',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='geophysics',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='gis',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='gis',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='gis',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='gis',
            name='path_filename_arche',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in ARCHE'),
        ),
        migrations.AddField(
            model_name='gis',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='gis',
            name='software_used',
            field=models.CharField(blank=True, max_length=250, verbose_name='Software used'),
        ),
        migrations.AddField(
            model_name='inventorybooks',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='inventorybooks',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='inventorybooks',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='inventorybooks',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='inventorybooks',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='inventorybooks',
            name='storage_folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage folder of original document'),
        ),
        migrations.AddField(
            model_name='phasenid',
            name='phase_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Phase ID'),
        ),
        migrations.AddField(
            model_name='phasenid',
            name='phase_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Phase title'),
        ),
        migrations.AddField(
            model_name='protocols',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='protocols',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='protocols',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='protocols',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='protocols',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='protocols',
            name='storage_folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage folder of original document'),
        ),
        migrations.AddField(
            model_name='stratenid',
            name='stratum_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Stratum ID'),
        ),
        migrations.AddField(
            model_name='stratenid',
            name='stratum_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Stratum title'),
        ),
        migrations.AddField(
            model_name='tables',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='tables',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='tables',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='tables',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='tables',
            name='folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Folder original'),
        ),
        migrations.AddField(
            model_name='tables',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='tdinv4dpuzzlenummer',
            name='tdinv4dpuzzlenummer_f',
            field=models.CharField(blank=True, max_length=250, verbose_name='TDInv4DPuzzleNUMMER_f'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year original'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='relatedto',
            field=models.CharField(blank=True, max_length=250, verbose_name='File is related to other TD resources'),
        ),
        migrations.AddField(
            model_name='threedimensionalmodel',
            name='software_used',
            field=models.CharField(blank=True, max_length=250, verbose_name='Created by software'),
        ),
        migrations.AddField(
            model_name='videos',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID '),
        ),
        migrations.AddField(
            model_name='videos',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='videos',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename '),
        ),
        migrations.AddField(
            model_name='videos',
            name='path_filename_arche',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in ARCHE'),
        ),
        migrations.AddField(
            model_name='videos',
            name='path_filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Data path in old TD archive'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='creation_year_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Creation year of original document'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='document_id',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document ID'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='document_title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Document title'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='filename',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='filename_old',
            field=models.CharField(blank=True, max_length=250, verbose_name='Filename old'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='fresco_inventory_number',
            field=models.CharField(blank=True, max_length=250, verbose_name='Fresco inventory number'),
        ),
        migrations.AddField(
            model_name='wallpaintinginventory',
            name='storage_folder_original',
            field=models.CharField(blank=True, max_length=250, verbose_name='Storage folder of original wallpainting'),
        ),
    ]
