# Generated by Django 5.0.6 on 2024-07-09 11:24

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FcCollection",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fc_fullname", models.TextField()),
                ("fc_name", models.TextField()),
                ("fc_ordername", models.CharField(blank=True, max_length=254)),
                ("fc_firstmod", models.DateTimeField(null=True)),
                ("fc_lastmod", models.DateTimeField(null=True)),
                ("fc_size", models.BigIntegerField(default=0)),
                ("fc_items", models.BigIntegerField(default=0)),
                ("fc_arche_id", models.TextField(blank=True)),
                ("fc_arche_description", models.TextField(blank=True)),
                ("fc_arche_access", models.TextField(blank=True)),
                ("fc_custom_rdf", models.TextField(blank=True)),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="filechecker.fccollection",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FcResource",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fc_fullname", models.TextField()),
                ("fc_filename", models.TextField(blank=True, null=True)),
                ("fc_lastmod", models.DateTimeField(null=True)),
                ("fc_size", models.BigIntegerField(blank=True, null=True)),
                ("fc_type", models.CharField(blank=True, max_length=254, null=True)),
                (
                    "fc_extension",
                    models.CharField(blank=True, max_length=254, null=True),
                ),
                ("fc_arche_cat", models.TextField(blank=True, null=True)),
                ("fc_arche_id", models.TextField(blank=True)),
                ("fc_arche_description", models.TextField(blank=True)),
                (
                    "fc_arche_access",
                    models.TextField(
                        blank=True,
                        help_text="If set blank a given value from the parent directory        is taken for the rdf serialisation",
                    ),
                ),
                ("fc_custom_rdf", models.TextField(blank=True)),
                (
                    "fc_directory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="has_fc_resource",
                        to="filechecker.fccollection",
                    ),
                ),
            ],
        ),
    ]
